name: Python Unit Tests

on:
  push:
    branches: [main, feature, test]
  pull_request:
    branches: [main, feature, test]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install html-testRunner  # if you’re using it

      - name: Run tests with unittest
        run: |
          python -m unittest discover -s projects/bowling -p "test_*.py"
