name: Python Unit Tests

on:
  push:
    branches: [main, feature/html-report]
  pull_request:
    branches: [main, feature/html-report]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run tests and generate HTML
        run: |
          python -m pip install --upgrade pip
          pip install html-testRunner
          python run_tests.py

      - name: Debug files
        run: ls -R # recursively list all files in the repo

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: unittest-report
          path: reports/unit-test-report.html
