name: Python Unit Tests and Docs

on:
  push:
    branches: [main, feature/html-report]
  pull_request:
    branches: [main, feature/html-report]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install html-testRunner pdoc
          python run_tests.py

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        with:
          name: unittest-report
          path: reports/unit-test-report_*.html

      - name: Generate pdoc documentation
        working-directory: projects/bowling
        run: |
          pdoc bowling_game test_bowling_game --output-dir docs

      - name: Commit and push updated docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "📄 Auto-update docs via GitHub Actions"
          git push
        continue-on-error: true # Don't fail if nothing changed
